export { default as AddUser } from './Add user.svg?react';
export { default as Add } from './Add.svg?react';
export { default as ArrowDown } from './Arrow down.svg?react';
export { default as ArrowLeft } from './Arrow left.svg?react';
export { default as ArrowRight } from './Arrow right.svg?react';
export { default as ArrowUp } from './Arrow up.svg?react';
export { default as BrightnessMax } from './Brightness Max.svg?react';
export { default as BrightnessMin } from './Brightness Min.svg?react';
export { default as Calendar } from './Calendar.svg?react';
export { default as Chat } from './Chat.svg?react';
export { default as Check } from './Check.svg?react';
export { default as ChevronDown } from './Chevron down.svg?react';
export { default as ChevronLeft } from './Chevron left.svg?react';
export { default as ChevronRight } from './Chevron right.svg?react';
export { default as ChevronUp } from './Chevron up.svg?react';
export { default as Clock } from './Clock.svg?react';
export { default as Contact } from './Contact.svg?react';
export { default as Cross } from './Cross.svg?react';
export { default as Delete } from './Delete.svg?react';
export { default as DesktopFraming } from './Desktop Framing.svg?react';
export { default as Disconnected } from './Disconnected.svg?react';
export { default as Download } from './Download.svg?react';
export { default as Edit } from './Edit.svg?react';
export { default as Envelope } from './Envelope.svg?react';
export { default as Ethernet } from './Ethernet.svg?react';
export { default as ExternalLink } from './External Link.svg?react';
export { default as Filter } from './Filter.svg?react';
export { default as Folder } from './Folder.svg?react';
export { default as Framing } from './Framing.svg?react';
export { default as GalleryView } from './Gallery View.svg?react';
export { default as Help } from './Help.svg?react';
export { default as HidePassword } from './Hide Password.svg?react';
export { default as ImageQuality } from './Image Quality.svg?react';
export { default as ImageSettings } from './Image Settings.svg?react';
export { default as Image } from './Image.svg?react';
export { default as Info } from './Info.svg?react';
export { default as LightMax } from './Light Max.svg?react';
export { default as LightMin } from './Light Min.svg?react';
export { default as MenuHamburger } from './Menu Hamburger.svg?react';
export { default as MenuKebab } from './Menu Kebab.svg?react';
export { default as MenuMeatball } from './Menu Meatball.svg?react';
export { default as Minus } from './Minus.svg?react';
export { default as Move } from './Move.svg?react';
export { default as PaneLeft } from './Pane Left.svg?react';
export { default as PaneRight } from './Pane Right.svg?react';
export { default as Plus } from './Plus.svg?react';
export { default as PortraitLighting } from './Portrait Lighting.svg?react';
export { default as Profile } from './Profile.svg?react';
export { default as Refresh } from './Refresh.svg?react';
export { default as Remove } from './Remove.svg?react';
export { default as SaturationMax } from './Saturation Max.svg?react';
export { default as SaturationMin } from './Saturation Min.svg?react';
export { default as Search } from './Search.svg?react';
export { default as Settings } from './Settings.svg?react';
export { default as ShowPassword } from './Show Password.svg?react';
export { default as SpeakerFraming } from './Speaker Framing.svg?react';
export { default as Subtract } from './Subtract.svg?react';
export { default as SuccessFilled } from './Success Filled.svg?react';
export { default as Success } from './Success.svg?react';
export { default as Update } from './Update.svg?react';
export { default as USB } from './USB.svg?react';
export { default as User } from './User.svg?react';
export { default as Users } from './Users.svg?react';
export { default as VideoCamera } from './Video Camera.svg?react';
export { default as WarningFilled } from './Warning Filled.svg?react';
export { default as Warning } from './Warning.svg?react';
export { default as WideAngle } from './Wide-angle.svg?react';
export { default as ZoomIn } from './Zoom In.svg?react';
export { default as ZoomOut } from './Zoom Out.svg?react';
